# Shared helpers for source-policy tests.

if(NOT DEFINED RTS_SOURCE_DIR OR "${RTS_SOURCE_DIR}" STREQUAL "")
    message(FATAL_ERROR "RTS_SOURCE_DIR is required")
endif()

function(rts_policy_read relative_path out_var)
    set(_path "${RTS_SOURCE_DIR}/${relative_path}")
    if(NOT EXISTS "${_path}")
        message(FATAL_ERROR "Required policy input is missing: ${relative_path}")
    endif()
    file(READ "${_path}" _contents)
    set(${out_var} "${_contents}" PARENT_SCOPE)
endfunction()

function(rts_policy_require_contains relative_path needle)
    if(ARGC GREATER 2)
        set(_description "${ARGV2}")
    else()
        set(_description "required text '${needle}' is missing")
    endif()
    rts_policy_read("${relative_path}" _contents)
    string(FIND "${_contents}" "${needle}" _pos)
    if(_pos EQUAL -1)
        message(FATAL_ERROR "Policy regression: ${_description} (${relative_path})")
    endif()
endfunction()

function(rts_policy_require_absent relative_path needle)
    if(ARGC GREATER 2)
        set(_description "${ARGV2}")
    else()
        set(_description "forbidden text '${needle}' is present")
    endif()
    rts_policy_read("${relative_path}" _contents)
    string(FIND "${_contents}" "${needle}" _pos)
    if(NOT _pos EQUAL -1)
        message(FATAL_ERROR "Policy regression: ${_description} (${relative_path})")
    endif()
endfunction()

function(rts_policy_require_text contents needle description)
    string(FIND "${contents}" "${needle}" _pos)
    if(_pos EQUAL -1)
        message(FATAL_ERROR "Policy regression: ${description}")
    endif()
endfunction()

function(rts_policy_forbid_text contents needle description)
    string(FIND "${contents}" "${needle}" _pos)
    if(NOT _pos EQUAL -1)
        message(FATAL_ERROR "Policy regression: ${description}")
    endif()
endfunction()
